## \u5F00\u53D1\u73AF\u5883\u914D\u7F6E
spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Yehong99.
    url: jdbc:mysql://localhost:3306/jwt_demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
  jackson:
    time-zone: GMT+8

# token \u7684\u6709\u6548\u65F6\u95F4\uFF081\u5929\uFF09\u548C \u79C1\u94A5
mydefine:
  token:
    expire: 86400
    signature: jwt-demo


#\u6253\u5370\u6267\u884C\u7684sql\u8BED\u53E5
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl