## 主配置文件
spring:
  profiles:
    active: dev
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8


mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml